# Generated by Django 3.0.8 on 2020-07-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fullname',
            new_name='username',
        ),
    ]
