# Generated by Django 3.0.8 on 2020-07-25 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200724_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='register',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
