# Generated by Django 3.0.8 on 2020-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200725_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
