# Generated by Django 3.0.8 on 2020-07-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200725_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], max_length=7)),
                ('pincode', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('gname', models.CharField(max_length=100)),
                ('gphone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=30)),
                ('ques', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], max_length=7),
        ),
        migrations.AlterField(
            model_name='register',
            name='ques',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
    ]
